# Generated by Django 4.0.2 on 2022-03-07 10:05
from django.db import migrations


def create_data(apps, schema_editor):
    file = apps.get_model('pages', 'File')
    file(file='users/nothing.png').save()


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
