# Generated by Django 4.0.2 on 2022-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.IntegerField(null=True),
        ),
    ]
