# Generated by Django 4.0.2 on 2022-03-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220307_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
