# Generated by Django 4.0.2 on 2022-02-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_article_page_delete_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='page',
            new_name='user',
        ),
    ]
