# Generated by Django 4.0.2 on 2022-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0005_remove_dialog_user'),
        ('authentication', '0004_user_age_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dialog',
            field=models.ManyToManyField(to='msgs.Dialog'),
        ),
    ]
