# Generated by Django 4.0.2 on 2022-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_alter_message_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
