# Generated by Django 4.0.2 on 2022-02-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_dialog_remove_message_receiver_message_dialog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='text',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='sender',
        ),
    ]
