# Generated by Django 4.0.2 on 2022-02-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0004_dialog_user_alter_message_dialog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='user',
        ),
    ]
